"""Initial migration.

Revision ID: 44596bacd120
Revises: 
Create Date: 2024-06-08 08:06:21.651585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44596bacd120'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_request', schema=None) as batch_op:
        batch_op.alter_column('influencer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('messages',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('campaign_request', schema=None) as batch_op:
        batch_op.alter_column('messages',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('influencer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
